export const INSURANCE_COMPANIES = [
  'GENIALLOYD',
  'VERTI',
  'CONTE',
  'PRIMA ASSICURAZIONI',
  'QUOTO',
  'WEASSURE',
  'CLICKASSICURA',
  'LINEAR',
  'YOUNDRIVE',
  'DIRECTLINE',
  'GENERALI',
  'ALLIANZ',
  'UNIPOLSAI',
  'AXA',
  'ZURICH',
  'HELVETIA',
  'REALE MUTUA',
  'SARA',
  'CATTOLICA',
  'ITAL ASSISTANCE',
  'FONDAZIONE SAIT',
  'GROUPAMA',
  'BROKERLINE',
  'ASSITECO',
  'AON',
  'MARSH',
  'WILLIS TOWERS WATSON',
  'BGL ASSICURAZIONI',
  'MEDIOLANUM',
  'ERGO',
  'HDI',
  'QBE',
  'CHUBB',
  'AIG',
  'LLOYD\'S',
  'VITTORIA',
] as const;

export const INSURANCE_CATEGORIES = [
  'Animali',
  'Casa',
  'Salute',
  'Infortuni',
  'Mezzi Storici',
  'Responsabilità Civile (RC)',
  'RC Professionale',
  'RC Prodotti',
  'Cyber Risk',
  'Danni a Terzi',
  'Furto',
  'Incendio',
  'Allagamento',
  'Eventi Atmosferici',
  'Impianti Elettrici',
  'Impianti Fotovoltaici',
  'Cantieri',
  'Macchinari',
  'Merci Trasportate',
  'Flotta Aziendale',
  'Autoveicoli',
  'Motoveicoli',
  'Mezzi Pesanti',
  'Viaggi',
  'Tutela Legale',
  'Assistenza Stradale',
  'Malattia',
  'Vita',
  'Previdenza',
  'Pensione Integrativa',
  'Rischi Diversi',
] as const;
