// Catalogo orientativo per impiantistica elettrica e fotovoltaica.
 // L'app non determina automaticamente obblighi, abilitazioni o scadenze:
 // dipendono da DVR, mansione, incarico, Regione e attestati individuali.
export interface TrainingCourseGroup {
  label: string;
  courses: readonly string[];
}

export const TRAINING_COURSE_GROUPS: readonly TrainingCourseGroup[] = [
  {
    label: 'Sicurezza generale e figure aziendali',
    courses: [
      'Formazione generale lavoratori',
      'Formazione specifica lavoratori - rischio basso',
      'Formazione specifica lavoratori - rischio medio',
      'Formazione specifica lavoratori - rischio alto',
      'Aggiornamento formazione lavoratori',
      'Formazione preposti',
      'Aggiornamento preposti',
      'Formazione dirigenti',
      'Aggiornamento dirigenti',
      'Formazione datore di lavoro',
      'Datore di lavoro RSPP',
      'RSPP - Modulo A',
      'RSPP - Modulo B',
      'RSPP - Modulo C',
      'ASPP - Moduli A e B',
      'Aggiornamento RSPP / ASPP',
      'RLS - formazione iniziale',
      'RLS - aggiornamento',
      'Addetto primo soccorso - Gruppo A',
      'Addetto primo soccorso - Gruppi B/C',
      'Aggiornamento primo soccorso',
      'Addetto antincendio - Livello 1',
      'Addetto antincendio - Livello 2',
      'Addetto antincendio - Livello 3',
      'Aggiornamento addetto antincendio',
      'BLSD / uso del defibrillatore',
    ],
  },
  {
    label: 'Rischio elettrico e norme CEI',
    courses: [
      'CEI 11-27:2025 - formazione lavori elettrici PES/PAV',
      'CEI 11-27:2025 - aggiornamento PES/PAV',
      'CEI 11-27 - addestramento pratico lavori elettrici 1B',
      'CEI 11-27 - addestramento pratico sotto tensione BT 2B',
      'CEI 11-27 - preparazione idoneita PEI per lavori sotto tensione BT',
      'CEI EN 50110-1 - esercizio degli impianti elettrici',
      'Rischio arco elettrico (Arc Flash) e DPI elettrici',
      'Procedure LOTO - sezionamento e messa in sicurezza',
      'Lavori in prossimita di linee elettriche',
      'Lavori fuori tensione MT/AT e cabine elettriche',
      'Manovre e procedure di sicurezza cabine MT/BT',
      'Misure elettriche, prove strumentali e ricerca guasti',
      'Verifiche impianti di terra e DPR 462/2001',
    ],
  },
  {
    label: 'Cantieri, lavori in quota e attrezzature',
    courses: [
      'Lavori in quota e prevenzione cadute',
      'DPI di III categoria - anticaduta: formazione e addestramento',
      'Recupero e soccorso operatore sospeso',
      'Uso sicuro scale portatili',
      'Uso trabattelli / ponti su ruote',
      'Montaggio, uso e smontaggio ponteggi - PIMUS',
      'Coordinatore sicurezza CSP/CSE',
      'Aggiornamento coordinatore sicurezza CSP/CSE',
      'Piattaforme di lavoro elevabili PLE - con stabilizzatori',
      'Piattaforme di lavoro elevabili PLE - senza stabilizzatori',
      'Aggiornamento abilitazione PLE',
      'Carrelli elevatori semoventi',
      'Gru per autocarro',
      'Gru mobili',
      'Macchine movimento terra',
      'Imbracatura e movimentazione dei carichi',
      'Segnalazione e coordinamento sollevamenti',
      'Spazi confinati / ambienti sospetti di inquinamento',
      'Cantieri temporanei e mobili - POS e procedure operative',
      'Rischio chimico e uso di sostanze pericolose',
      'Movimentazione manuale carichi e rischio ergonomico',
    ],
  },
  {
    label: 'Fotovoltaico, FER e accumulo',
    courses: [
      'Installatori FER - qualificazione per sistemi fotovoltaici',
      'Installatori FER - aggiornamento settore fotovoltaico',
      'Progettazione impianti fotovoltaici - guida CEI 82-25',
      'Installazione meccanica e strutturale moduli fotovoltaici',
      'Installazione FV su coperture e sicurezza anticaduta',
      'Sezionamento DC e sicurezza stringhe fotovoltaiche',
      'Norma CEI 64-8 - Sezione 712 fotovoltaico',
      'Verifiche e collaudi FV - CEI EN IEC 62446-1',
      'Messa in servizio e diagnostica inverter fotovoltaici',
      'Connessione alla rete - CEI 0-21 (BT)',
      'Connessione alla rete - CEI 0-16 (MT/AT)',
      'Protezioni interfaccia SPI e verifiche di connessione',
      'Installazione e sicurezza sistemi di accumulo BESS',
      'Rischio incendio e gestione emergenze su batterie al litio',
      'Termografia e ricerca guasti su impianti FV',
      'Manutenzione preventiva e monitoraggio impianti FV',
      'Prevenzione incendi per impianti fotovoltaici',
      'Documentazione tecnica, dichiarazione conformita e DM 37/2008',
    ],
  },
  {
    label: 'Impiantistica elettrica specialistica e automazione',
    courses: [
      'CEI 64-8 - progettazione, realizzazione e verifiche impianti BT',
      'CEI EN 61439 - quadri elettrici BT',
      'Impianti MT/BT e dimensionamento trasformatori',
      'Protezioni differenziali, SPD e coordinamento protezioni',
      'Illuminazione di emergenza e verifiche periodiche',
      'Impianti EV / colonnine - CEI 64-8 Sezione 722',
      'KNX - building automation',
      'BMS e sistemi di supervisione edifici',
      'PLC e automazione industriale',
      'DALI e progettazione illuminotecnica',
      'Cablaggio strutturato e reti dati',
      'Fibra ottica - posa, giunzione e test',
      'Centrale antincendio e sistemi di rivelazione',
      'Videosorveglianza, controllo accessi e GDPR',
      'Cybersecurity di reti industriali e sistemi OT',
      'BIM impiantistico e modellazione elettrica',
    ],
  },
  {
    label: 'Organizzazione del lavoro e competenze trasversali',
    courses: [
      'Gestione commesse e avanzamento lavori',
      'Lettura schemi elettrici e disegni esecutivi',
      'Qualita, collaudo e non conformita',
      'Gestione materiali, logistica e magazzino',
      'Guida sicura di veicoli aziendali',
      'Protezione dati e privacy GDPR',
      'Sicurezza informatica e phishing',
      'Gestione emergenze in cantiere',
      'Uso DPI specifici del cantiere',
      'Formazione su attrezzature e procedure aziendali',
    ],
  },
];

export const TRAINING_COURSE_TITLES = TRAINING_COURSE_GROUPS.flatMap((group) => group.courses);
